# Site settings
title: P Srivatsa
email: p.psrivatsa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A bit about myself
baseurl:  # the subpath of your site, e.g. /blog/
url:  https://psrivatsa.com
github_username:  sri-vatsa

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
plugins:
  - jekyll-paginate
paginate: 1
paginate_path: "/blog/page:num/"


